## Intel NUC installation
- name: Apply pre-requisite configuration to all nodes
  hosts: intel-nuc-all
  roles:
    - common-prereq-software

## Install Docker
- name: Install Docker
  hosts: intel-nuc-all
  roles:
    - thirdparty-docker

## Install Virtualbox
- name: Install Virtualbox
  hosts: intel-nuc-all
  roles:
    - thirdparty-virtualbox
