## Intel NUC installation
- name: Apply pre-requisite configuration to all nodes
  hosts: all
  roles:
    - common-prereq-software

## Install Docker
- name: Install Docker
  hosts: all
  roles:
    - thirdparty-docker

## Install Virtualbox
- name: Install Virtualbox
  hosts: all
  roles:
    - thirdparty-virtualbox

## Install Synology Drive Client
- name: Install Synology Drive Client
  hosts: all
  roles:
    - thirdparty-synology-drive-client

## Install chrome
- name: Install chrome
  hosts: all
  roles:
    - thirdparty-chrome