## Intel NUC installation
- name: Apply pre-requisite configuration to all nodes
  hosts: all
  roles:
    - common-prereq-software

## Install Docker
- name: Install Docker
  hosts: intel_nuc
  roles:
    - thirdparty-docker

## Install Virtualbox
- name: Install Virtualbox
  hosts: intel_nuc
  roles:
    - thirdparty-virtualbox
