---
# Install Intel NUC basic software packages

  # Install basic tools
  - name: Install basic tools
    package: name={{item}} state=present
    with_items:
      - epel-release
      - net-tools
      - wget
      - yum-utils
      - git
      - curl
      - zsh
  
  # Stop and disable firewalld
  - name: Stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no

  - name: Create user and add to groups
    user:
      name: "martijn"
      #groups: "sudo martijn wheel docker"
      shell: /bin/zsh

  # Secure ssh
  - name: Import the sshkey for the new user
    authorized_key:
      user: "martijn"
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8c3uZAc1s+uxfaKdmWbAzxhCRSesUCFKWfpdm0o7R8FKS+VUMxk8xAso+/H9jxsPfC+IO/bDeIYYAtrx/yZ7AKsucI22wvg8WEAZdaZpRbK214HRSwkVpfKNihUFi/JE0BiCScjkF1DPmfiApYZLTelJyoU68AJgaWG0i6khq+YwXI2ON5SXpPblvIASqD20LljTLjcus69ZhzoQAgWJ8ixE/eLDXnxwwqwUK8gMnCNzYblemyZ6roV4e24qjw9IE7lpc47yO3MuKoTtVMqwqzdAn1W3yMQIReChEBJYRTaJsQUFQjBr+jELkbSNhJv8nJn7OOO9yd/+jygYZ+NtX"

  - name: Disable using passwords for SSH
    lineinfile: dest=/etc/ssh/sshd_config line='PasswordAuthentication no' state=present

  - name: Disable SSH login for root
    lineinfile: dest=/etc/ssh/sshd_config line='PermitRootLogin no' state=present

  - name: Restarting the SSH service
    service: name=sshd state=restarted

  - name: Install fail2ban
    package: name=fail2ban state=present

  - name: Start and disable fail2ban
    systemd:
      name: fail2ban
      state: started
      enabled: yes

  # Install a Minimal Desktop environment
  - name: Install minimal desktop
    yum:
      name: "@X Window System"
      state: present

  - name: Install minimal desktop prerequisites
    package: name={{item}} state=present
    with_items:
      - gnome-classic-session
      - gnome-terminal
      - nautilus-open-terminal
      - control-center
      - liberation-mono-fonts

  - name: Desktop environment - Create a symbolic link
    file:
      src: /lib/systemd/system/graphical.target
      dest: /etc/systemd/system/default.target
      state: link

#  - name: install the 'GNOME Desktop' package group
#    yum:
#      name: "@^GNOME Desktop"
#      state: present
