---
# Install Intel NUC basic software packages
  
  # Install basic tools
  - name: Install basic tools
    package: name={{item}} state=present
    with_items:
      - epel-release
      - net-tools
      - wget
      - yum-utils

  # Install a Minimal Desktop environment
  - name: Install basic tools
    yum: name={{item}} state=present
    with_items:
      - "@^X Window System"
      - gnome-classic-session
      - gnome-terminal
      - nautilus-open-terminal
      - control-center
      - liberation-mono-fonts

  - name: Desktop environment - Create a symbolic link
    file:
      src: /etc/systemd/system/default.target
      dest: /lib/systemd/system/graphical.target
      state: link
#unlink /etc/systemd/system/default.target
#ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target
#reboot

#  - name: install the 'GNOME Desktop' package group
#    yum:
#      name: "@^GNOME Desktop"
#      state: present

  # Install xrdp for remote access
  - name: Install basic tools
    package: name=xrdp state=present

  # Launch xrdp service for remote access
  - name: Start the xrdp service
    systemd:
      name: xrdp
      state: started
      enabled: yes
      daemon_reload: yes
