---
# Install Intel NUC basic software packages

  # Install basic tools
  - name: Install basic tools
    package: name={{item}} state=present
    with_items:
    #  - epel-release
      - net-tools
    #  - wget
    #  - yum-utils
      - git
      - curl
      - zsh


  # Create the custom network config file
  - name: Create the custom network config file
    blockinfile:
      path: /tmp/netplan.yaml
      create: yes
      block: |
        network:
          version: 2
          renderer: networkd
          ethernets:
            eno1:
              dhcp4: no
              addresses:
                - 192.168.1.3/24
              gateway4: 192.168.1.1
              nameservers:
                  addresses: [192.168.1.4, 8.8.8.8]

  # Create the custom network config file
  - name: Create the custom network config file
    copy:
      src: /tmp/netplan.yaml
      dest: /etc/netplan/00-installer-config.yaml
      owner: root
      group: root
      mode: '0644'
      backup: yes


  
  # Stop and disable firewalld
  # - name: Stop and disable firewalld
  #   systemd:
  #     name: firewalld
  #     state: stopped
  #     enabled: no

  - name: Create user and add to groups
    user:
      name: "martijn"
      #groups: "sudo martijn wheel docker"
      shell: /bin/bash
      #shell: /bin/zsh

  - name: Allow user to run various sudo commands
    lineinfile:
      path: /etc/sudoers.d/martijn
      line: 'martijn ALL=(ALL) NOPASSWD:/sbin/shutdown,/sbin/reboot,/sbin/halt,/usr/sbin/shutdown,/usr/sbin/reboot,/usr/sbin/halt'
      state: present
      create: yes

  # Secure ssh
  - name: Import the sshkey for the new user
    authorized_key:
      user: "martijn"
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8c3uZAc1s+uxfaKdmWbAzxhCRSesUCFKWfpdm0o7R8FKS+VUMxk8xAso+/H9jxsPfC+IO/bDeIYYAtrx/yZ7AKsucI22wvg8WEAZdaZpRbK214HRSwkVpfKNihUFi/JE0BiCScjkF1DPmfiApYZLTelJyoU68AJgaWG0i6khq+YwXI2ON5SXpPblvIASqD20LljTLjcus69ZhzoQAgWJ8ixE/eLDXnxwwqwUK8gMnCNzYblemyZ6roV4e24qjw9IE7lpc47yO3MuKoTtVMqwqzdAn1W3yMQIReChEBJYRTaJsQUFQjBr+jELkbSNhJv8nJn7OOO9yd/+jygYZ+NtX"

  - name: Disable using passwords for SSH
    lineinfile: dest=/etc/ssh/sshd_config line='PasswordAuthentication no' state=present

  - name: Disable SSH login for root
    lineinfile: dest=/etc/ssh/sshd_config line='PermitRootLogin no' state=present

  - name: Restarting the SSH service
    service: name=sshd state=restarted

  - name: Install fail2ban
    package: name=fail2ban state=present

  - name: Start and enable fail2ban
    systemd:
      name: fail2ban
      state: started
      enabled: yes

  # Install a Minimal Desktop environment
  
  # ubuntu
  - name: Install desktop
    #package: name=ubuntu-desktop state=present
    package: name={{item}} state=present
    with_items:
      - xfce4
      - xfce4-goodies
#      - ubuntu-desktop-minimal

  # - name: Autologin to the desktop on boot for user martijn
  #   replace:
  #     path: /etc/gdm3/custom.conf
  #     regexp: '#  AutomaticLoginEnable = true'
  #     replace: 'AutomaticLoginEnable = true'

  # - name: Autologin to the desktop on boot for user martijn
  #   replace:
  #     path: /etc/gdm3/custom.conf
  #     regexp: '#  AutomaticLogin = user1'
  #     replace: 'AutomaticLogin = martijn'


  # # Create the auto launch directory if it does not exist
  # - name: Create the auto launch directory if it does not exist
  #   file:
  #     path: /home/martijn/.config/autostart/
  #     state: directory
  #     owner: martijn
  #     group: martijn
  #     mode: '0755'

  # # Create the auto launch file if it does not exist
  # - name: Create the auto launch file if it does not exist
  #   file:
  #     path: /home/martijn/.config/autostart/vncserver.desktop
  #     state: touch
  #     owner: martijn
  #     group: martijn
  #     mode: '0755'

  # # Launch vncserver on boot and login for user martijn
  # - name: Launch vncserver on boot and login for user martijn
  #   blockinfile:
  #     path: /home/martijn/.config/autostart/vncserver.desktop
  #     block: |
  #       [Desktop Entry]
  #       Type=Application
  #       Name=vncserver
  #       Exec=vncserver -localhost no -geometry 1680x1050 -depth 32
  #       Icon=<full path to icon>
  #       Comment=Launch vncserver
  #       X-GNOME-Autostart-enabled=true

  # centos
  # - name: Install minimal desktop
  #   yum:
  #     name: "@X Window System"
  #     state: present

  # - name: Install minimal desktop prerequisites
  #   package: name={{item}} state=present
  #   with_items:
  #     - gnome-classic-session
  #     - gnome-terminal
  #     - nautilus-open-terminal
  #     - control-center
  #     - liberation-mono-fonts

  # - name: Desktop environment - Create a symbolic link
  #   file:
  #     src: /lib/systemd/system/graphical.target
  #     dest: /etc/systemd/system/default.target
  #     state: link
